import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
import { adarsh, amelia, amulya, james, natasha, noah, shubham } from ".";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: "hdjksahdkjas_hjkdgs",
    avatarUrl: amulya,
    firstName: "Amulya",
    lastName: "Parab",
    bio: "Always covered in cat hair, but it's a fashion statement, right?",
    website: "https://e-commerce-main-project.vercel.app/",
    occupation: "Software Developer",
    username: "amulyaparab",
    password: "amulyaparab123",
    email: "amulyaparab123@gmail.com",
    createdAt: "2020-09-15T08:20:45+05:30",
    updatedAt: formatDate(),
    // bookmarks: [],
    // followedBy: [],
    // following: [],
  },
  {
    _id: "dsghfgs_mkdfjl",
    avatarUrl: amelia,
    firstName: "Amelia",
    lastName: "Smith",
    bio: "Spending quality time with my fur baby 🐾",
    website: "https://e-commerce-main-project.vercel.app/",
    occupation: "Software Developer",
    username: "ameliasmith",
    password: "ameliasmith123",
    email: "ameliasmith123@gmail.com",
    createdAt: "2020-11-18T16:26:45+05:30",
    updatedAt: formatDate(),
    // bookmarks: [],
    // followedBy: [],
    // following: [],
  },
  {
    _id: "aowimdsmdjaldk_dksj",
    avatarUrl: noah,
    firstName: "Noah",
    lastName: "Martinez",
    bio: "Obsessed with all things feline.",
    website: "https://e-commerce-main-project.vercel.app/",
    occupation: "Software Developer",
    username: "noahmartinez",
    password: "noahmartinez123",
    email: "noahmartinez123@gmail.com",
    createdAt: "2020-10-08T14:33:37+05:30",
    updatedAt: formatDate(),
    // bookmarks: [],
    // followedBy: [],
    // following: [],
  },

  {
    _id: "sahdkjas_kjkojoi",
    avatarUrl: shubham,
    firstName: "Shubham",
    lastName: "Soni",
    bio: "My cat's eyes are windows to a world of love and curiosity.",
    website: "https://e-commerce-main-project.vercel.app/",
    occupation: "Software Developer",
    username: "shubhamsoni",

    password: "shubhamsoni123",
    email: "shubhamsoni123@gmail.com",
    createdAt: "2018-06-07T20:52:07+05:30",
    updatedAt: formatDate(),
    // bookmarks: [],
    // followedBy: [],
    // following: [],
  },
  {
    _id: "haskjdhas_khdiuas",
    avatarUrl: james,
    firstName: "James",
    lastName: "Davis",
    bio: "Proud servant to a demanding feline overlord.",
    website: "https://e-commerce-main-project.vercel.app/",
    occupation: "Software Developer",
    username: "jamesdavis",
    password: "jamesdavis123",
    email: "jamesdavis123@gmail.com",
    createdAt: "2020-11-18T16:26:45+05:30",
    updatedAt: formatDate(),
    // bookmarks: [],
    // followedBy: [],
    // following: [],
  },
  {
    _id: "asdkhyasui_sajdaois",
    avatarUrl: natasha,
    firstName: "Natasha",
    lastName: "Iyer",
    bio: "Catnip: the secret to a happy life! 🌿",
    website: "https://e-commerce-main-project.vercel.app/",
    occupation: "Software Developer",
    username: "natashaiyer",
    password: "natashaiyer123",
    email: "natashaiyer123@gmail.com",
    createdAt: "2019-11-28T19:05:52+05:30",
    updatedAt: formatDate(),
    // bookmarks: [],
    // followedBy: [],
    // following: [],
  },
  {
    _id: "iwopeiwq_kjhds",
    avatarUrl: adarsh,
    firstName: "Adarsh",
    lastName: "Sharma",
    bio: "Cat whisperer: decoding the language of meows and purrs.",
    website: "https://e-commerce-main-project.vercel.app/",
    occupation: "Software Developer",
    username: "adarshsharma",
    password: "adarshsharma123",
    email: "adarshsharma123@gmail.com",
    createdAt: "2019-12-15T01:17:30+05:30",
    updatedAt: formatDate(),
    // bookmarks: [],
    // followedBy: [],
    // following: [],
  },
];
